/*  AUTH AND USER ACTIONS  */
export const ITEMS_LOADING = 'ITEMS_LOADING'
export const USER_LOADING = 'USER_LOADING'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const FINISH_REGISTER = 'FINISH_REGISTER'
export const UPDATE_FAVOURITE = 'UPDATE_FAVOURITE'
export const UPDATE_PAST_ORDERS = 'UPDATE_PAST_ORDERS'
/*  ERRORS ACRTIONS        */
export const GET_ERRORS = 'GET_ERRORS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
/*  CART ACTIONS        */
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const ADD_ONE_TO_CART = 'ADD_ONE_TO_CART'
export const REORDER = 'REORDER'
export const CLEAR_CART = 'CLEAR_CART'
export const CLEAR_CART_AFTER_CHECKOUT = 'CLEAR_CART_AFTER_CHECKOUT'
export const CHECKOUT_FINISHED = 'CHECKOUT_FINISHED'

/* STRIPE ACTIONS */
export const SAVE_PAYMENT_METHOD = 'SAVE_PAYMENT_METHOD'

/* PASTA ACTIONS */
export const SET_PASTA = 'SET_PASTA'
export const IS_LOADING = 'IS_LOADING'
